#!/bin/sh
#arg1: video input directory
./notify /home/gobolin/video-input/ &
echo 'Encoder Started' &

#arg1:input directory (same as ./notify) arg2: video output arg3: google bucket mount point arg4: user who mounted the google bucket
python3 main.py /home/gobolin/video-input/ /home/gobolin/video-output /home/gobolin/mock-google/ gobolin